"use client";
import { useCallback, useEffect, useState, useRef } from "react";
import { REVIEW_CHANNELS, type ReviewChannel, type ReviewRow, type ReviewSource, type analysisSchema } from "@/lib/recipe-reviews/model";
import type { z } from "zod";
type Stats={count:number;ratedCount:number;average:number|null;distribution:{star:number;count:number}[]};
type Data={sources:ReviewSource[];stats:Stats;byChannel:Record<ReviewChannel,Stats>;reviews:ReviewRow[];total:number;collection:{created_at:string;result:{sources:{channel:ReviewChannel;productKey:string;status:string;message:string;count:number}[]}}|null;analysis:{stale:boolean;created_at:string;result:z.infer<typeof analysisSchema>&{analyzedCount:number;totalCount:number;selection:string;evidence:ReviewRow[]}}|null;jobs:{id:string;status:string;task_key:string;progress:number;current_step:string;error_message:string|null}[]};
const statusLabels:Record<string,string>={queued:"実行待ち",running:"実行中",completed:"完了",needs_review:"一部未取得・確認あり",waiting_for_user:"操作待ち",failed:"失敗",cancelled:"取消",complete:"取得完了",partial:"一部取得",blocked:"未取得",no_reviews:"レビューなし"};
export default function RecipeReviews({recipeId}:{recipeId:string}){
 const [channel,setChannel]=useState<ReviewChannel|"all">("all"),[page,setPage]=useState(0),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [source,setSource]=useState<ReviewSource>({channel:"amazon",productKey:"",name:"",url:""});
 const requestSeq=useRef(0);
 const load=useCallback(async()=>{const seq=++requestSeq.current;const r=await fetch(`/api/recipe/${recipeId}/reviews?channel=${channel}&page=${page}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);if(seq===requestSeq.current)setData(d);},[recipeId,channel,page]);
 const polling=!!data?.jobs.some(j=>["queued","running"].includes(j.status));
 useEffect(()=>{let stopped=false;const refresh=()=>load().catch(e=>{if(!stopped)setError(e.message)});void refresh();const timer=polling?setInterval(refresh,15000):null;return()=>{stopped=true;if(timer)clearInterval(timer)};},[load,polling]);
 async function act(mode:string){setBusy(true);setError("");setNotice("");try{const r=await fetch(`/api/recipe/${recipeId}/reviews`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,source})});const d=await r.json();if(!r.ok)throw new Error(d.error);setNotice(mode==="source"?"収集元を保存しました":"Bridgeに依頼しました。事務所PCで順次実行します。");await load();}catch(e){setError(e instanceof Error?e.message:"処理に失敗しました")}finally{setBusy(false)}}
 const active=data?.jobs.some(j=>["queued","running"].includes(j.status));const scope=data?.analysis?.result.scopes.find(s=>s.channel===channel);
 return <section className="mx-auto max-w-[1400px] p-4 md:p-8 space-y-6" aria-label="商品レビュー">
 <div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-2xl font-bold">商品レビュー</h2><p className="text-sm text-gray-600 mt-2">ECの商品レビューを収集・保存し、良い点、課題、改善案を分析します。</p></div><div className="flex gap-2 items-start"><button className="rounded bg-slate-900 text-white px-4 py-3 disabled:opacity-40" disabled={busy||active} onClick={()=>void act("collect")}>各ECを巡回・収集して分析</button><button className="border rounded px-4 py-3 disabled:opacity-40" disabled={busy||active||!data?.analysis&& !Object.values(data?.byChannel??{}).some(s=>s.count)} onClick={()=>void act("analyze")}>保存済みレビューを再分析</button></div></div>
 <p className="text-sm text-gray-600">1回の巡回は各商品最大200件。ページ制限・ログイン待ちなどは「未取得」として残します。全体集約は、このレシピに紐付く各ECの保存済みレビューが対象です。</p>
 {error&&<p role="alert" className="bg-red-50 text-red-800 p-3 rounded">{error}</p>}{notice&&<p role="status" className="bg-blue-50 p-3 rounded">{notice}</p>}
 {!!data?.jobs.length&&<div className="rounded border p-3 space-y-2">{data.jobs.slice(0,3).map(j=><p key={j.id} className="text-sm"><strong>{j.task_key.endsWith("collect")?"収集":"分析"}：{statusLabels[j.status]||j.status}</strong> {j.progress}% · {j.current_step}{j.error_message&&<span className="text-red-700"> · {j.error_message}</span>}</p>)}</div>}
 <div role="tablist" aria-label="レビュー対象EC" className="flex flex-wrap gap-2">{[["all","全体集約"],...Object.entries(REVIEW_CHANNELS)].map(([key,label])=><button role="tab" aria-selected={channel===key} key={key} onClick={()=>{setChannel(key as ReviewChannel|"all");setPage(0)}} className={`px-5 py-3 rounded-lg font-bold ${channel===key?"bg-slate-900 text-white":"bg-slate-100"}`}>{label}{key!=="all"&&data?` (${data.byChannel[key as ReviewChannel].count})`:""}</button>)}</div>
 {!data?<p>レビューを読み込み中…</p>:<>
 <div className="grid sm:grid-cols-3 gap-3"><div className="border rounded-lg p-4"><p>保存レビュー</p><strong className="text-3xl">{data.stats.count}件</strong></div><div className="border rounded-lg p-4"><p>平均評価（評価のある{data.stats.ratedCount}件）</p><strong className="text-3xl">{data.stats.average?.toFixed(2)??"—"}</strong><p className="text-xs text-gray-500">保存分の平均。EC画面の全評価平均とは異なります。</p></div><div className="border rounded-lg p-4">{data.stats.distribution.map(d=><p key={d.star} className="text-sm">★{d.star}：{d.count}件</p>)}</div></div>
 <section className="border rounded-xl p-5 bg-blue-50/40"><h3 className="text-xl font-bold">レビュー傾向・改善案</h3>{scope?<><p className="text-xs text-gray-500 mt-2">分析日時：{new Date(data.analysis!.created_at).toLocaleString("ja-JP")} / 全EC合計 {data.analysis!.result.totalCount}件中{data.analysis!.result.analyzedCount}件を分析</p>{data.analysis!.stale&&<p className="bg-amber-100 p-2 mt-2 font-bold">分析後にレビューが更新されています。最新の分析は実行状況を確認してください。</p>}<p className="text-sm mt-2">{data.analysis!.result.selection}</p><p className="whitespace-pre-wrap mt-4">{scope.summary}</p><div className="grid md:grid-cols-3 gap-4 mt-5">{([["strengths","評価されている点"],["issues","不満・課題"],["actions","改善・訴求の提案"]] as const).map(([key,label])=><div key={key}><h4 className="font-bold text-lg">{label}</h4>{scope[key].length?scope[key].map((t,i)=><div key={i} className="mt-3 bg-white border rounded p-3"><strong>{t.title}</strong><p className="text-sm mt-2 whitespace-pre-wrap">{t.description}</p><details className="mt-2 text-sm"><summary className="cursor-pointer text-blue-700">根拠レビュー {t.reviewIds.length}件</summary>{t.reviewIds.map(id=>{const r=data.analysis?.result.evidence?.find(r=>r.id===id);return r?<div key={id} className="border-t mt-2 pt-2"><a href={r.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">{REVIEW_CHANNELS[r.channel]} · {r.title||"原文を見る"}</a><p className="whitespace-pre-wrap">{r.body}</p></div>:<p key={id}>根拠ID：{id}</p>})}</details></div>):<p className="text-sm mt-2">根拠のある指摘なし</p>}</div>)}</div><p className="mt-4 text-sm text-amber-900">分析の範囲・注意点：{scope.limitations}</p></>:<p className="mt-3 text-gray-600">{data.stats.count?"まだ分析結果がありません。収集後に自動で分析されます。":"この対象の保存済みレビューはありません。収集状況も確認してください。"}</p>}</section>
 <section><h3 className="text-xl font-bold mb-3">レビュー原文</h3>{data.reviews.map(r=><article key={r.id} className="border rounded-lg bg-white p-4 mb-3"><div className="flex justify-between gap-3 text-sm text-gray-600"><span>{REVIEW_CHANNELS[r.channel]} · {r.rating==null?"評価値なし":`★${r.rating}`} · {r.posted_at||"投稿日不明"}</span><a href={r.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">掲載元</a></div><h4 className="font-bold mt-2">{r.title}</h4><p className="whitespace-pre-wrap break-words mt-2">{r.body}</p><p className="text-xs text-gray-500 mt-2">商品番号：{r.product_key} / 取得：{new Date(r.collected_at).toLocaleString("ja-JP")}</p></article>)}{!data.total&&<p>レビュー0件（取得済みかどうかは下記の収集状況を確認）</p>}<div className="flex gap-4 items-center"><button disabled={!page} className="border px-3 py-2 rounded disabled:opacity-40" onClick={()=>setPage(p=>p-1)}>前へ</button><span>{page+1} / {Math.max(1,Math.ceil(data.total/30))}</span><button disabled={(page+1)*30>=data.total} className="border px-3 py-2 rounded disabled:opacity-40" onClick={()=>setPage(p=>p+1)}>次へ</button></div></section>
 <details className="border rounded p-4" open={!data.sources.length}><summary className="font-bold cursor-pointer">収集元・取得状況</summary><p className="text-sm mt-2">商品紐付けから取得します。紐付けがない場合は正しい商品番号とECのURLを登録してください。</p>{Object.entries(REVIEW_CHANNELS).filter(([c])=>!data.sources.some(s=>s.channel===c)).map(([c,label])=><p key={c} className="text-amber-800 mt-2">{label}：商品紐付け未設定（レビューなしとは異なります）</p>)}{data.sources.map(s=>{const result=data.collection?.result.sources.find(r=>r.channel===s.channel&&r.productKey===s.productKey);return <div key={s.channel+s.productKey} className="mt-2 border-t pt-2 text-sm"><strong>{REVIEW_CHANNELS[s.channel]} / {s.productKey}</strong> {s.name}<p>{result?`${statusLabels[result.status]}：${result.count}件 · ${result.message}`:"未収集"}</p><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">収集元</a></div>})}<div className="grid sm:grid-cols-2 gap-3 mt-4"><label>EC<select className="border rounded p-2 w-full" value={source.channel} onChange={e=>setSource(s=>({...s,channel:e.target.value as ReviewChannel}))}>{Object.entries(REVIEW_CHANNELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{([['productKey','商品番号 / ASIN'],['name','商品名'],['url','商品・レビューページURL']] as const).map(([k,label])=><label key={k}>{label}<input className="border rounded p-2 w-full" value={source[k]} onChange={e=>setSource(s=>({...s,[k]:e.target.value}))}/></label>)}</div><button disabled={busy} className="border rounded px-4 py-2 mt-3" onClick={()=>void act("source")}>収集元を登録・更新</button></details>
 </>}
 </section>;
}
